--자바 CallableStatement 테스트
DROP TABLE EMP1;
CREATE TABLE EMP1
AS
SELECT EMPLOYEE_ID, FIRST_NAME, DEPARTMENT_ID, SALARY FROM EMPLOYEES;

SELECT * FROM EMP1 ORDER BY DEPARTMENT_ID;

CREATE OR REPLACE PROCEDURE BOOKS_PROC(VID IN BOOKS.ID%TYPE, VPRICE IN BOOKS.PRICE%TYPE,
    VMESSAGE OUT VARCHAR2)
IS
    VBOOKS_RT BOOKS%ROWTYPE;
BEGIN
    UPDATE BOOKS SET PRICE = PRICE+VPRICE
    WHERE ID = VID;
    COMMIT;
    SELECT * INTO VBOOKS_RT FROM BOOKS WHERE ID = VID;
    VMESSAGE := VBOOKS_RT.ID||'번호의 인상금액은 '||VPRICE||'이고 총 금액은C'||VBOOKS_RT.PRICE||'입니다.';
    DBMS_OUTPUT.PUT_LINE(VMESSAGE);
END;
/
VARIABLE MESSAGE VARCHAR2(100);
EXECUTE BOOKS_PROC(7,10000,:MESSAGE);
SELECT * FROM BOOKS;
ROLLBACK;

DESC EMP1;
