--PL/SQL
--EMPLOYEE에서 부서번호를 랜덤으로 생성한뒤 해당된 부서번호의 최고연봉을 출력한뒤, 평가하여라(낮음,높음,중간,최고,없음)
DECLARE
   VNUM1 NUMBER := 1;
   VNUM2 NUMBER := 1;
BEGIN
    LOOP
        DBMS_OUTPUT.PUT_LINE('****구구단 '||VNUM1||'단****');
        LOOP
            DBMS_OUTPUT.PUT_LINE(VNUM1||'*'||VNUM2||'='||(VNUM1*VNUM2));
            VNUM2 := VNUM2 + 1;
            IF(VNUM2>9) THEN
                EXIT;
            END IF;
        END LOOP;
        VNUM1 := VNUM1+1;
        VNUM2 := 1;
        IF(VNUM1 >9) THEN
            EXIT;
        END IF;
    END LOOP;
END;
/

--1. EMPLOYEES 테이블에 등록된 총사원의 수와 급여의 합, 급여의 평균을 변수를 대입하여 출력
DECLARE
    VCOUNT NUMBER;
    VSALARY_SUM NUMBER;
    VSALARY_AVG NUMBER;
BEGIN
    SELECT COUNT(*), SUM(SALARY), ROUND(AVG(SALARY)) INTO VCOUNT,VSALARY_SUM,VSALARY_AVG FROM EMPLOYEES;
    DBMS_OUTPUT.PUT_LINE('총사원의 수 : '||VCOUNT);
    DBMS_OUTPUT.PUT_LINE('급여의 합 : '||VSALARY_SUM);
    DBMS_OUTPUT.PUT_LINE('급여의 평균 : '||VSALARY_AVG);
END;
/

--2. Clara 사원의 직무,급여,입사일자,커미션,부서명을 변수에 대입하여 출력
DECLARE
    VFIRST_NAME EMPLOYEES.FIRST_NAME%TYPE;
    VJOB_ID EMPLOYEES.JOB_ID%TYPE;
    VSALARY EMPLOYEES.SALARY%TYPE;
    VHIRE_DATE EMPLOYEES.HIRE_DATE%TYPE;
    VCOMMISSION_PCT EMPLOYEES.COMMISSION_PCT%TYPE;
    VDEPARTMENT_NAME DEPARTMENTS.DEPARTMENT_NAME%TYPE;
BEGIN
    SELECT FIRST_NAME, JOB_ID, SALARY, HIRE_DATE, COMMISSION_PCT, DEPARTMENT_NAME
    INTO VFIRST_NAME, VJOB_ID, VSALARY, VHIRE_DATE, VCOMMISSION_PCT, VDEPARTMENT_NAME
    FROM EMPLOYEES E INNER JOIN DEPARTMENTS D ON e.department_id=d.department_id
    WHERE FIRST_NAME = 'Clara';

    DBMS_OUTPUT.PUT_LINE('이름 : '||VFIRST_NAME);
    DBMS_OUTPUT.PUT_LINE('직무 : '||VJOB_ID);
    DBMS_OUTPUT.PUT_LINE('급여 : '||VSALARY);
    DBMS_OUTPUT.PUT_LINE('입사일자 : '||VHIRE_DATE);
    DBMS_OUTPUT.PUT_LINE('커미션 : '||VCOMMISSION_PCT);
    DBMS_OUTPUT.PUT_LINE('부서명 : '||VDEPARTMENT_NAME);
END;
/

