--EMPLOYEES 복사
CREATE TABLE EMP03
AS 
SELECT * FROM EMPLOYEES;
--모든 사원 부서번호 수정
SELECT * FROM EMP03;
UPDATE EMP03 SET DEPARTMENT_ID=30;
ROLLBACK;
--모든 사원 급여 10% 인상
UPDATE EMP03
SET SALARY = SALARY*1.1;
--입사일 오늘로 수정
UPDATE EMP03
SET HIRE_DATE = SYSDATE;
--부서번호가 10번인 사원 30번으로 수정
UPDATE EMP03
SET DEPARTMENT_ID = 30
WHERE DEPARTMENT_ID = 10;
--급여가 3000이상인 사원 급여 10% 인상
UPDATE EMP03
SET SALARY=SALARY*1.1
WHERE SALARY>=3000;