--STORED PROCEDURE
DROP TABLE EMP01;
CREATE TABLE EMP01
AS
SELECT * FROM EMPLOYEES;
SELECT * FROM EMP01;

--부서별로 월급을 인상하는 프로그램. 10번부터 전원10%%인상, 20번부서 전원 20%인상, 나머지는 동결

CREATE OR REPLACE PROCEDURE EMP01_PROC(VDEPTID IN EMP01.DEPARTMENT_ID%TYPE)
IS
BEGIN
IF VDEPTID = 10 THEN
        UPDATE EMP01 SET SALARY = SALARY*1.1 WHERE DEPARTMENT_ID=VDEPTID;
        DBMS_OUTPUT.PUT_LINE(VDEPTID||'부서 월급 전원 10% 인상하였습니다.');
    ELSIF VDEPTID = 20 THEN
        UPDATE EMP01 SET SALARY = SALARY*1.2 WHERE DEPARTMENT_ID=VDEPTID;        
        DBMS_OUTPUT.PUT_LINE(VDEPTID||'부서 월급 전원 20% 인상하였습니다.');
    ELSE
        DBMS_OUTPUT.PUT_LINE(VDEPTID||'부서 월급 전원 동결입니다.');    
    END IF;
END;
/

EXECUTE EMP01_PROC(30);

