--STORED PROCEDURE
--매개변수 있는 PROCEDURE
create or replace NONEDITIONABLE PROCEDURE EMP_PROC2(VWORD IN VARCHAR2)
IS
    VEMP_ROWTYPE EMPLOYEES%ROWTYPE;
    CURSOR C_NAME(VWORD VARCHAR2)
    IS
    SELECT * FROM EMPLOYEES WHERE UPPER(FIRST_NAME) LIKE UPPER('%'||VWORD||'%');
BEGIN
    FOR VEMP_ROWTYPE IN C_NAME(VWORD) LOOP
        DBMS_OUTPUT.PUT_LINE(VEMP_ROWTYPE.FIRST_NAME||'/'||VEMP_ROWTYPE.SALARY);
    END LOOP;
END;
/

EXECUTE EMP_PROC2('D');
