--테이블 설계하기:DDL
--class EMP01{
--    PRIVATE INT NO;
--    PRIVATE STRING NAME;
--    PRIVATE DOUBLE SALARY;
--    }
CREATE TABLE EMP01(
    NO NUMBER(4) NOT NULL,
    NAME VARCHAR2(20) NOT NULL,
    SALARY NUMBER(10,2) DEFAULT 1000.0,
    CONSTRAINT EMP01_NO_PK PRIMARY KEY(NO),
    CONSTRAINT EMP01_NAME_UK UNIQUE(NAME)
);