--테이블 설계하기:DDL
--class EMP01{
--    PRIVATE INT NO;
--    PRIVATE STRING NAME;
--    PRIVATE DOUBLE SALARY;
--    }
CREATE TABLE EMP01(
    NO NUMBER(4) NOT NULL,
    NAME VARCHAR2(20) CONSTRAINT EMP01_NAME_NN NOT NULL,
    SALARY NUMBER(10,2) DEFAULT 1000.0,
    CONSTRAINT EMP01_NO_PK PRIMARY KEY(NO),
    CONSTRAINT EMP01_NAME_UK UNIQUE(NAME)
);
--테이블 정보 구하기
SELECT * FROM TAB;
--테이블 삭제하기 DDL DROP
DROP TABLE EMP01;

--휴지통보기
SELECT * FROM RECYCLEBIN;
--PURGE RECYCLEBIN;
--복원하기
FLASHBACK TABLE EMP01 TO BEFORE DROP;

--테이블 복사하기(제약조건은 복사 안됨, NOT NULL만 됨)
DESC EMPLOYEES;
SELECT COUNT(*) FROM EMPLOYEES;
CREATE TABLE EMPLE02
AS

SELECT * FROM EMPLOYEES;
DESC EMPLE02;
SELECT COUNT(*) FROM EMPLE02;
--제약조건 추가 PRIMARY KEY, UNIQUE
ALTER TABLE EMPLE02 ADD CONSTRAINT EMPLE02_ID_PK PRIMARY KEY(EMPLOYEE_ID);
ALTER TABLE EMPLE02 ADD CONSTRAINT EMPLE02_EMAIL_UK UNIQUE(EMAIL);
--제약조건 삭제하기
ALTER TABLE EMPLE02 DROP CONSTRAINT EMPLE02_EMAIL_UN;
--제약조건 조회
SELECT * FROM USER_CONSTRAINTS;
SELECT TABLE_NAME,CONSTRAINT_NAME,CONSTRAINT_TYPE FROM USER_CONSTRAINTS WHERE TABLE_NAME = UPPER('EMPLE02');
--컬럼추가 EMP01
ALTER TABLE EMP01 ADD JOB VARCHAR2(10) NOT NULL;
DESC EMP01;
--컬럼 제거
ALTER TABLE EMP01 DROP COLUMN JOB;
--컬럼 변경(기존값이 존재할때는 주의->타입변경불가, 사이즈는 큰것으로 변경 가능)
ALTER TABLE EMP01 MODIFY JOB NUMBER(10) DEFAULT 0;
--컬럼 이름 변경
ALTER TABLE EMP01 RENAME COLUMN JOB TO JOB2;

--테이블명을 변경 EMP01->EMP02 DDL CREATE, ALTER, DROP, RENAME, TRUNC
RENAME EMP01 TO EMP02;
SELECT * FROM TAB;

CREATE TABLE CUSTOMER(
    CUST_ID CHAR(7) NOT NULL,
    CUST_NAME VARCHAR2(10) NOT NULL,
    GENDER CHAR(1) NOT NULL,
    BIRTHDAY CHAR(8) NOT NULL,
    TEL VARCHAR2(16),
    EMAIL VARCHAR2(30),
    POINT NUMBER(10) DEFAULT 0
--    CONSTRAINT CUSTOMER_CUST_ID__PK PRIMARY KEY(CUST_ID),
--    CONSTRAINT CUSTOMER_EMAIL_UK UNIQUE(EMAIL),
--    CONSTRAINT CUSTOMER_GENDER_CK CHECK(GENDER IN('M','W'))
);
ALTER TABLE CUSTOMER DROP CONSTRAINT CUSTOMER_CUST_ID__PK;
ALTER TABLE CUSTOMER DROP CONSTRAINT CUSTOMER_EMAIL_UK;
ALTER TABLE CUSTOMER DROP CONSTRAINT CUSTOMER_GENDER_CK;

ALTER TABLE CUSTOMER ADD CONSTRAINT CUSTOMER_CUST_ID_PK PRIMARY KEY(CUST_ID);
ALTER TABLE CUSTOMER ADD CONSTRAINT CUSTOMER_EMAIL_UK UNIQUE(EMAIL);
ALTER TABLE CUSTOMER ADD CONSTRAINT CUSTOMER_GENDER_CK CHECK(GENDER IN('M','W'));

SELECT * FROM TAB;
DESC CUSTOMER;
SELECT * FROM USER_CONSTRAINTS WHERE TABLE_NAME = 'CUSTOMER';

