CREATE TABLE SCORE(
    STU_ID NUMBER(10) NOT NULL,
    STU_NAME VARCHAR2(10) NOT NULL,
    KOR NUMBER(3)  DEFAULT 0 NOT NULL,
    ENG NUMBER(3)  DEFAULT 0 NOT NULL,
    MATH NUMBER(3)  DEFAULT 0 NOT NULL,
    TOTAL NUMBER(3) DEFAULT 0,
    AVG NUMBER(5,2) DEFAULT 0.0,
    CODE VARCHAR2(10),
    CONSTRAINT SCORE_STU_ID_PK PRIMARY KEY(STU_ID)
);

CREATE TABLE MAJOR(
    CODE VARCHAR2(10) NOT NULL,
    NAME VARCHAR2(10) NOT NULL,
    CONSTRAINT MAJOR_CODE_PK PRIMARY KEY(CODE)
);

--foreign key 적용 방법
ALTER TABLE SCORE ADD CONSTRAINT SCORE_MAJOR_CODE_FK FOREIGN KEY(CODE) REFERENCES MAJOR(CODE) ON DELETE CASCADE; 


SELECT * FROM EMPLOYEES;

SELECT NVL2(MANAGER_ID,MANAGER_ID,0) 
FROM EMPLOYEES
WHERE MANAGER_ID IS NULL;

SELECT FIRST_NAME, DEPARTMENT_ID,
    CASE WHEN DEPARTMENT_ID=10 THEN 'Administration'
     WHEN DEPARTMENT_ID=20 THEN 'Marketing'
     WHEN DEPARTMENT_ID=30 THEN 'Purchasing'
     WHEN DEPARTMENT_ID=40 THEN 'Human Resources'
     WHEN DEPARTMENT_ID=50 THEN 'Shipping'
     WHEN DEPARTMENT_ID=60 THEN 'IT'
    END DEPARTMENT_NAME,
    DECODE(DEPARTMENT_NAME, 'Marketing', SALARY*1.05)
FROM EMPLOYEES
ORDER BY DEPARTMENT_ID;

--조인(INNER JOIN, OUTER JOIN, SELF JOIN, CROSS JOIN)
SELECT * FROM DEPARTMENTS;
SELECT EMPLOYEE_ID, FIRST_NAME, SALARY, DEPARTMENT_ID FROM EMPLOYEES;

SELECT EMPLOYEE_ID, FIRST_NAME, JOB_ID, SALARY, E.DEPARTMENT_ID, DEPARTMENT_NAME,
        CASE WHEN UPPER(D.DEPARTMENT_NAME) = UPPER('Marketing') THEN SALARY*1.05
             WHEN UPPER(D.DEPARTMENT_NAME) = UPPER('Purchasing') THEN SALARY*1.1
             WHEN UPPER(D.DEPARTMENT_NAME) = UPPER('Human Resources') THEN SALARY*1.15
             WHEN UPPER(D.DEPARTMENT_NAME) = UPPER('IT') THEN SALARY*1.2
             ELSE SALARY
             END NEWSALARY
FROM EMPLOYEES E INNER JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID;

SELECT EMPLOYEE_ID, FIRST_NAME, JOB_ID, 
    DECODE(DEPARTMENT_NAME, 'Marketing', SALARY*1.05, 'Purchasing', SALARY*1.1, 'Human Resources', SALARY*1.15, 'IT', SALARY*1.2)
    AS NEWSALARY
FROM EMPLOYEES E INNER JOIN DEPARTMENTS D ON E.DEPARTMENT_ID=D.DEPARTMENT_ID
WHERE DEPARTMENT_NAME IN('Marketing','IT','Human Resources','Purchasing');

--다른 문제
DESC EMP01;
ALTER TABLE EMP01 ADD CREDATE DATE;
ALTER TABLE EMP01 MODIFY JOB_ID VARCHAR2(30) NOT NULL;
 
