CREATE TABLE MEMBER(
    NO NUMBER(5),
    NAME VARCHAR2(15),
    ID VARCHAR2(15),
    PASSWORD VARCHAR2(20),
    PHONE VARCHAR2(14),
    ADDRESS VARCHAR2(50)
);

CREATE SEQUENCE MEMBER_SEQ
    START WITH 1
    INCREMENT BY 1;
    
INSERT INTO MEMBER VALUES(MEMBER_SEQ.NEXTVAL, 'KIM','ID','PWD','PHONE','ADDRESS');

select * from member;
delete from member;