--개인 회원가입 테이블
CREATE TABLE CUSTOMER(
    ID          VARCHAR2(15),
    PWD         VARCHAR2(15) NOT NULL,
    NAME        VARCHAR2(15) NOT NULL,
    PHONE1      VARCHAR2(3)   NOT NULL,
    PHONE2      VARCHAR2(4)   NOT NULL,
    PHONE3      VARCHAR2(4)   NOT NULL,
    EMAIL       VARCHAR2(50)   NOT NULL,
    ZIPCODE     VARCHAR2(7)   NOT NULL,
    ADDRESS1    VARCHAR2(100)  NOT NULL,
    ADDRESS2    VARCHAR2(50)    NOT NULL
);
ALTER TABLE CUSTOMER ADD CONSTRAINTS CUSTOMER_ID_PK PRIMARY KEY(ID); 
SELECT * FROM CUSTOMER;
SELECT * FROM CUSTOMER WHERE ID='a';
SELECT * FROM CUSTOMER;
UPDATE SET CUSTOMER PWD = ? NAME = ? PHONE1 = ? PHONE2 = ? PHONE3 = ? EMAIL = ? ZIPCODE = ? ADDRESS1 = ? ADDRESS2 = ?;
SELECT EMAIL FROM CUSTOMER;
SELECT ID,PWD,NAME,PHONE1,PHONE2,PHONE3,SUBSTR(EMAIL, 1, INSTR(EMAIL,'@' ,-1)-1),ZIPCODE,ADDRESS1,ADDRESS2 FROM CUSTOMER;
SELECT EMAIL, INSTR(EMAIL, '@', -1) from CUSTOMER;
SELECT * FROM ZIPCODE WHERE DONG = '강남%';

--답변형 게시판
CREATE TABLE  BOARD (
    NUM     NUMBER(7,0) NOT NULL, 
    WRITER  VARCHAR2(12) NOT NULL, 
    EMAIL   VARCHAR2(30) NOT NULL, 
    SUBJECT VARCHAR2(50) NOT NULL, 
    PASS    VARCHAR2(10) NOT NULL, 
    READCOUNT NUMBER(5,0) DEFAULT 0, 
    "REF"   NUMBER(5,0) DEFAULT 0, 
    STEP    NUMBER(3,0) DEFAULT 0, 
    "DEPTH" NUMBER(3,0) DEFAULT 0, 
    REGDATE TIMESTAMP (6) DEFAULT SYSDATE, 
    "CONTENT" VARCHAR2(4000) NOT NULL, 
    IP      VARCHAR2(20) NOT NULL
   );
   
CREATE SEQUENCE BOARD_SEQ  -- 시퀀스이름
   START WITH 1                -- 시작을 1로 설정
   INCREMENT BY 1             -- 증가값을 1씩 증가
   NOMAXVALUE               -- 최대값이 무한대..
   NOCACHE
   NOCYCLE;
   
ALTER TABLE BOARD ADD CONSTRAINTS BOARD_NUM_PK PRIMARY KEY(NUM); 
select count(*) as count from board;
SELECT * FROM BOARD;
update board set readcount=0 where num = 1;
commit;

--상품 테이블
CREATE TABLE PRODUCT(
    NUM NUMBER(5),
    NAME VARCHAR2(50),
    PRICE NUMBER(10)
);
DROP TABLE PRODUCT;
DELETE FROM PRODUCT;
ALTER TABLE PRODUCT ADD CONSTRAINTS PRODUCT_NUM_PK PRIMARY KEY(NUM);
INSERT INTO PRODUCT VALUES(10001, '가죽자켓', 70000);
INSERT INTO PRODUCT VALUES(10002, '가죽자켓', 'M', 'BLACK', 70000);
INSERT INTO PRODUCT VALUES(10003, '가죽자켓', 'L', 'BLACK', 70000);
INSERT INTO PRODUCT VALUES(10004, '가죽자켓', 'S', 'WHITE', 70000);
INSERT INTO PRODUCT VALUES(10005, '가죽자켓', 'M', 'WHITE', 70000);
INSERT INTO PRODUCT VALUES(10006, '가죽자켓', 'L', 'WHITE', 70000);
SELECT * FROM PRODUCT;

--장바구니 테이블
CREATE TABLE BASKET(
    NUM NUMBER(10),
    C_ID VARCHAR2(15),
    P_NUM NUMBER(5),
    "SIZE" VARCHAR2(10),
    COLOR VARCHAR2(10)
);
DROP TABLE BASKET;
ALTER TABLE BASKET ADD CONSTRAINTS BASKET_NUM_PK PRIMARY KEY(NUM);
ALTER TABLE BASKET ADD CONSTRAINTS BASKET_C_ID_FK FOREIGN KEY(C_ID) REFERENCES CUSTOMER(ID);
ALTER TABLE BASKET ADD CONSTRAINTS BASKET_P_NUM_FK FOREIGN KEY(P_NUM) REFERENCES PRODUCT(NUM);
COMMIT;
SELECT * FROM USER_CONSTRAINTS ;

DROP SEQUENCE BASKET_SEQ;
CREATE SEQUENCE BASKET_SEQ
    START WITH 1
    INCREMENT BY 1;

INSERT INTO BASKET VALUES(BASKET_SEQ.NEXTVAL, 'a', 10001, 'S', 'BLACK');

SELECT B.NUM, B.C_ID, B.P_NUM, B."SIZE", B.COLOR,  P.NAME, P.PRICE FROM BASKET B INNER JOIN PRODUCT P ON B.P_NUM=P.NUM WHERE C_ID='s';
SELECT * FROM BASKET B INNER JOIN PRODUCT P ON B.P_NUM=P.NUM; 